server:
  port: 8080

spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    default-property-inclusion: non_empty


  datasource:
    url: jdbc:postgresql://ec2-75-101-128-10.compute-1.amazonaws.com:5432/d5jjchg7av06iq?autoReconnect=true&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: opuqnhskxvtxsz
    password: 28c9088170f4ca6360847a3e11a4107e0c36374a9c86fbfbe313a44ec8701e7c

  jpa:
    openInView: false
    show_sql: true
    generate-ddl: true
      #hibernate:
    # ddl-auto: create-drop
    properties:
      # fixes Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
      hibernate.jdbc.lob.non_contextual_creation: true

  data:
    jpa:
      repositories.enabled: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.example: DEBUG

